### ISSUE TITLE
Need way to deal with scales on frontend and backend

### ISSUE THREAD

**Issue by grtlr** [visdesignlab/intent-system#105]
I have the feeling we should guarantee that the frontend and the backend work with the same scales.

**Comment by grtlr** [comment]
#108 is a first step in the right direction, but only works if the axes are scaled linearly.

**Comment by kirangadhave** [comment]
All the scales we have are scaled linearly for now

**Comment by alexsb** [comment]
Yes. We're not doing view transformations into log for now.
