### ISSUE TITLE
Request new predictions when axis is added/removed?

### ISSUE THREAD

**Issue by grtlr** [visdesignlab/intent-system#106]
![outlier](https://user-images.githubusercontent.com/3404250/63960016-b8e64480-ca4a-11e9-980e-53e6a285d18e.gif)

In the original configuration (with 3 axes) there are 2 ooutliers. Once we remove the _Deck_ axis, there is only one more outlier, however, the prediction do not update.

**Comment by kirangadhave** [comment]
I already request for new predictions when a axis is added or removed.
