### ISSUE TITLE
Disabling "show categories" should inactivate the category selection drop-down. 

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#141]
![image](https://user-images.githubusercontent.com/2039375/68340872-783b2500-00a4-11ea-84cf-097991be6690.png)

This should be grayed out, and to the right of show categories. We probably don't need "color" here either. Finally, it should default select the first categorical variable.

**Comment by kirangadhave** [comment]
Yes i have grayed it out, it selects first by default. The only reason i show it is to have it ready if we include a new dataset with multiple categories. Its all in the new pull request which travis is running tests on
