### ISSUE TITLE
Prediction for brushes, does not consider all the visible columns.

### ISSUE THREAD

**Issue by kirangadhave** [visdesignlab/intent-system#151]
Point selection considers all the dimensions for visible scatterplots.
Brush selection don't do this.

**Comment by kirangadhave** [comment]
According to a discussion with @alexsb, we can consider running algorithms on multiple combinations of dimensions:

- Dimensions of the plot which has the interaction
- Dimensions of plots which do not have interaction, but were visible when interaction was done.
- If multiple plots have interactions, run on combinations.

**Comment by grtlr** [comment]
@kirangadhave I just looked at the provenance information that gets send to the server. When we remove a plot, there is an additional interaction that I can't make much sense of:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/3404250/69224512-ff949800-0b7c-11ea-9f1c-0a7513f85c64.png">

Do you know what is going on here?
