### ISSUE TITLE
Add synthetic datasets

### ISSUE THREAD

**Issue by kirangadhave** [visdesignlab/intent-system#158]
Synthetic datasets to have clear patterns like clusters, corelation with outliers, etc.

**Comment by alexsb** [comment]
Other Datasets Needed: 

* [ ] A linear correlation dataset where we have a three pairs of dimensions: A strong, medium, and loose correlation. 
* [ ] A quadratic correlation dataset where we have a couple of different versions. 
* [ ] A cluster dataset with a bit more noise; or just add a two noisy cluster dimensions to the current cluster dataset.
