### ISSUE TITLE
Pick colors:

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#177]
Regular point: black, opacity 0.7
Selected point: #d95f0e (orange), opacity 0.9
Union point: #2c7fb8 (blue), opacity 0.9
Predicted point: reduce opacity of all other points to 0.2

**Comment by kirangadhave** [comment]
<img width="896" alt="Screen Shot 2019-11-26 at 12 40 09 PM" src="https://user-images.githubusercontent.com/14944083/69666693-e3479e00-1049-11ea-9aaa-66340d8bfb04.png">

This is how it looks after applying above points

**Comment by kirangadhave** [comment]
<img width="896" alt="Screen Shot 2019-11-26 at 1 07 25 PM" src="https://user-images.githubusercontent.com/14944083/69668733-b301fe80-104d-11ea-9040-eecb992b0984.png">

Opacity of 0.05 for non algorithm predictions works well

**Comment by kirangadhave** [comment]
<img width="896" alt="Screen Shot 2019-11-26 at 1 14 19 PM" src="https://user-images.githubusercontent.com/14944083/69669223-aa5df800-104e-11ea-97ee-4cac5ac9be0b.png">

**Comment by alexsb** [comment]
Looks great!
