### ISSUE TITLE
Make sure heroku is always responsive

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#183]
Or move to a different server. We don't want to wait that long.

**Comment by kirangadhave** [comment]
@grtlr Should we consider AWS? I think the major issue here is Heroku instance shutsdown if not used for a while.

**Comment by grtlr** [comment]
Sure, AWS would be fine (I have never worked with it though). Because everything we do is in Docker it basically boils down to:

```
docker build -t vdl/intent-system .
docker run -p 5000:5000 -it vdl/intent-system:latest
```

I run this setup locally in our LAN. Let me know if you need any help setting things up.

**Comment by kirangadhave** [comment]
Switched to AWS. Closing this
