### ISSUE TITLE
Beautify Tool-Tips

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#186]
Current status: 

![image](https://user-images.githubusercontent.com/2039375/69590811-f147e100-0fad-11ea-8c9f-6e5953851352.png)

Should show prominently the label
In bold at the top of the list: the values of the current scatterplot's dimensions.. 
Below: the values in other dimensions

**Comment by kirangadhave** [comment]
![Screen Shot 2019-11-26 at 12 02 12 PM](https://user-images.githubusercontent.com/14944083/69663954-99a88480-1044-11ea-977d-8c071b02bd44.png)


Does this work?

**Comment by alexsb** [comment]
Looks great; can you make the two active dimensions bold?

**Comment by kirangadhave** [comment]
<img width="896" alt="Screen Shot 2019-11-26 at 1 26 15 PM" src="https://user-images.githubusercontent.com/14944083/69670088-548a4f80-1050-11ea-8d40-de5aae2e4c10.png">

**Comment by alexsb** [comment]
And sort so that the bold ones are at the top. Then done!

**Comment by kirangadhave** [comment]
<img width="896" alt="Screen Shot 2019-11-26 at 1 45 12 PM" src="https://user-images.githubusercontent.com/14944083/69671291-fad75480-1052-11ea-870c-1aca8c4aac3a.png">


Done!
