### ISSUE TITLE
Change categorical mapping from colors to symbols

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#188]
https://github.com/d3/d3-shape#symbols

**Comment by kirangadhave** [comment]
This is turning out to be harder than expected. The d3 symbols return a generated path which has no center. It's difficult to update brushes to detect these symbols have been brushed

**Comment by kirangadhave** [comment]
![Screen Shot 2019-11-29 at 12 00 39 PM](https://user-images.githubusercontent.com/14944083/69886580-dd4afa80-129f-11ea-9c1a-6d4fbb6d48c8.png)

**Comment by kirangadhave** [comment]
Never mind, solved the issue
![Screen Shot 2019-11-29 at 12 06 15 PM](https://user-images.githubusercontent.com/14944083/69886728-a6291900-12a0-11ea-8f89-f6ebb76deb61.png)
