### ISSUE TITLE
Add "Simplified Range" Prediction

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#203]
We want to be able to generalize a range query dynamically for selection. To this end, add a "simplify selection" query to the range prediction, which should prune the decision tree by one level.

**Comment by alexsb** [comment]
Alternatively, let's just add a "simplified range" intent that prunes the tree and is then treated by the back-end just like any other prediction.

**Comment by grtlr** [comment]
I think this is a front-end issue. I'm already sending a simplified range-query in the `suggestion` field (only if tree has depth larger 1). I'll move the card to Kirans stack.

**Comment by alexsb** [comment]
We need to treat it as a separate intent and rank it though.

**Comment by grtlr** [comment]
It should be ranked already as well. The whole suggestion is a finished intent it just needs to be displayed. Maybe we should have it in a different color/style, then it wouldn’t make sense to send it just like a regular intent. In the end this decision is up to you, I can do both.

**Comment by alexsb** [comment]
Really? I have only seen this in the info box right now. I think it should just be called "Simplified Range", and be ranked according to jaccard/bayes, as it doesn't make sense to use the range ranking for it.

**Comment by grtlr** [comment]
It’s only in the info box right now, but it is exactly the same Json that is used to create the other intents. It just needs to be displayed. I’ll check if the rank prediction takes the depth of the tree into account for this intent as well-it does not look like it right now. If we choose to send it as a regular intent, we would have to make sure that it always stays with the original intent (maybe right below it). Parsing the info field would give us more flexibility (and might generalize better to other suggestions, UIs).

**Comment by alexsb** [comment]
I'd just like to see how it does as a regular intent. I'm not sure it needs to be treated special. If it's easy (which I assume it is) we should just try that.
