### ISSUE TITLE
Prediction doesn't work when data has null or negative values.

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#204]
![image](https://user-images.githubusercontent.com/2039375/69826575-f9339b00-11d0-11ea-9aa8-600eff76c3b2.png)

I can't reproduce in other configurations?

**Comment by alexsb** [comment]
It seems to be caused by a null or negative value. 

![image](https://user-images.githubusercontent.com/2039375/69826720-9e4e7380-11d1-11ea-8ee6-5cbff4c50712.png)

**Comment by grtlr** [comment]
I don't know what caused this but it seems to be fixed.
