### ISSUE TITLE
Improve Visuals for Prediction Interface

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#210]
Here's the current interface: 

![image](https://user-images.githubusercontent.com/2039375/69886633-226f2c80-12a0-11ea-81dc-e9e70bf2638d.png)

Suggestions: 

 * [x] Move (i) button to the right, this is detailed information. Right now it's easy to unintentionally hover over it. 
 * [x] Make the dimensions markers into "tags", for example, by surrounding them with a rounded rectangle, similar to github labels: 
![image](https://user-images.githubusercontent.com/2039375/69886684-68c48b80-12a0-11ea-9170-6781d681a6fc.png)
* [x] Add a tool-tip to the dimension markers revealing the full name of the dimension.
* [x] Make the text for containment bold, and add a semicolon after each statement like this: *M:* 1; *NP:* 1; *NS:* 0.
* [x] Allow me to hover over each of those statements, give me a tool-tip for the full name (Match, ...) and highlight the corresponding set on hover.

**Comment by kirangadhave** [comment]
@alexsb can you clarify the final point:

> Allow me to hover over each of those statements, give me a tool-tip for the full name (Match, ...) and highlight the corresponding set on hover.

Does this mean that the points in predictions should be highlighted on hover rather than click?

**Comment by kirangadhave** [comment]
> Make the dimensions markers into "tags", for example, by surrounding them with a rounded rectangle, similar to github labels:

Should we add another column for dimension, the prediction names for Quadratic and Linear are too long to show all the data

**Comment by kirangadhave** [comment]
Current status:

![Screen Shot 2019-11-29 at 1 07 55 PM](https://user-images.githubusercontent.com/14944083/69888475-43884b00-12a9-11ea-8ee7-b09b4ceca852.png)

**Comment by alexsb** [comment]
Regarding
> Allow me to hover over each of those statements, give me a tool-tip for the full name (Match, ...) and highlight the corresponding set on hover.

What I mean is two things:
 1. It's not immediately obvious what M, NP, NS means, so we need a tool-tip to clarify. 
 2. Each of these three expression identifies a set of points. Hovering over M: 38, for example, should highlight those 38 points. Hovering over NP: 4, should highlight those four points.

**Comment by alexsb** [comment]
> Should we add another column for dimension, the prediction names for Quadratic and Linear are too long to show all the data

That could work well, yes.

**Comment by alexsb** [comment]
Re current status, looks good, but there is an alignment issue with the numbers? They are superscript?

**Comment by kirangadhave** [comment]
I see it now, i am not sure. The only styling is to change font-weight of containment text to bold.

**Comment by kirangadhave** [comment]
Okay fixed the superscript issue, i had to surround the text in a tspan tag

**Comment by kirangadhave** [comment]
![Screen Shot 2019-11-29 at 1 22 27 PM](https://user-images.githubusercontent.com/14944083/69888848-4ab05880-12ab-11ea-913e-7b57b38730d0.png)

**Comment by kirangadhave** [comment]
![Screen Shot 2019-11-29 at 1 53 15 PM](https://user-images.githubusercontent.com/14944083/69889691-982ec480-12af-11ea-9c0a-d9b40dc143fe.png)

How's this?

**Comment by alexsb** [comment]
Looks good, but a bit wide?  Maybe Truncate "Dimension" To "Dim.". 

Also, do we have a more-than-two-dimension example?

**Comment by kirangadhave** [comment]
Yup testing

**Comment by kirangadhave** [comment]
![Screen Shot 2019-11-29 at 1 58 56 PM](https://user-images.githubusercontent.com/14944083/69889854-6407d380-12b0-11ea-8e37-2bb02fd67522.png)

With 4 dimensions

**Comment by alexsb** [comment]
Looks good. 

Btw, we could also make the M, NP, NS more "tag-like", so that it's obvious that you can hover on them.

**Comment by kirangadhave** [comment]
Again should we add another column, because the names are really long and some of the M, NS and NP tags go out of view. The bars are svgs so its a pain to make it scrollable

**Comment by kirangadhave** [comment]
Another benefit of having seperate column for this containment info is making it hoverable. Right now its a svg text, so i cannot add hover effect to individul text elements.

**Comment by alexsb** [comment]
Yes, I guess then we could go as far as having a column for each catgory and avoid the M NS lables all together.

**Comment by kirangadhave** [comment]
![Screen Shot 2019-11-29 at 7 52 53 PM](https://user-images.githubusercontent.com/14944083/69894777-d644dc00-12e1-11ea-92a4-34dfacb01a07.png)
![Screen Shot 2019-11-29 at 7 53 04 PM](https://user-images.githubusercontent.com/14944083/69894778-dcd35380-12e1-11ea-904f-8481227d9d42.png)
![Screen Shot 2019-11-29 at 7 53 16 PM](https://user-images.githubusercontent.com/14944083/69894781-e361cb00-12e1-11ea-84b7-6a9732baaa46.png)
![Screen Shot 2019-11-29 at 8 00 17 PM](https://user-images.githubusercontent.com/14944083/69894862-de514b80-12e2-11ea-8060-3f6f4281f547.png)
