### ISSUE TITLE
Don't do A-B and B-A for clusters, categorical, etc.

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#219]
Permuting dimensions only seems to make sense for regression, does it?

**Comment by alexsb** [comment]
This will be less problematic once #222 is implemented, but we should still do it.

**Comment by grtlr** [comment]
I don't think this needs fixing. The current state is that, in addition to all visible dimensions, only the visible combination of dimensions is considered.

**Comment by alexsb** [comment]
The result of this: 
![image](https://user-images.githubusercontent.com/2039375/69918436-1b2a5900-142f-11ea-8916-5def5f0f7bc9.png)

The first two rows are exactly the same cluster, with exactly the same algo and parametrization.
