### ISSUE TITLE
Remove duplicate predictions server-side

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#222]
Our original plan was to remove duplicate predictions client-side, but one downside of this is that it negatively affects they probabilities: right now, if we have 3 identical clusters, they split the probabilities. 

So consequently, this needs to be de-duplicated before the ranking. 

I suggest the following rule: 

Within an intent (e.g., cluster, independent of which algo or parameter was used) report only a single identical prediction. For now, we could just choose a random one. 

Down the line we could use a smarter approach; either reporting all algo configs that result in the same cluster, or reporting the one that has the best score, such as silhouette values.

**Comment by grtlr** [comment]
@alexsb That makes sense. However, I want to make a different approach that makes full use of the probabilistic framework: How about we only define the basic intents as class labels. Then, each output of the algorithms with different parameters just becomes one training example for the class. Once we know which basic intent we are in, we can learn a more detailed classifier for each of the parameter combinations. Or rank them using Jaccard.

**Comment by grtlr** [comment]
Adding to this, I think in this case the term we are looking for is hierarchical naive bayes, or hierarchical bayes methods. I have found a couple of papers on this, maybe there is a way to do this in `sklearn`.

**Comment by alexsb** [comment]
I'm not sure that is all that helpful. I think of these multiple results with exactly the same output set mostly as noise. Also, my suggestion is a 2-3 liner :).
