### ISSUE TITLE
Update Label of Not-regression 

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#228]
Right now it only shows "quadratic regression", but it should say "outside of quadratic regression". 

I assume the same is true for linear regression. 

Here's an example: 

![image](https://user-images.githubusercontent.com/2039375/69918607-752c1e00-1431-11ea-98a6-4587cf96801d.png)

**Comment by kirangadhave** [comment]
![Screen Shot 2019-12-01 at 12 45 23 PM](https://user-images.githubusercontent.com/14944083/69919274-73198d80-1438-11ea-9af1-7e2ff725471c.png)

@alexsb Does this work?

**Comment by alexsb** [comment]
I'd probably call it "Outside Lin. Reg." and "Outside Quad. Reg." .

**Comment by kirangadhave** [comment]
There is not enough space i think on a smaller screen

**Comment by kirangadhave** [comment]
Nope it fits. Pushing this too.
