### ISSUE TITLE
Simplified Intent Not Labeled and Not Properly Ranked

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#246]
See this example: 
![image](https://user-images.githubusercontent.com/2039375/70198661-abd19500-16cc-11ea-84ea-10dd7b11f665.png)

The top ranked intent shows "range", but has only a single rule in there. I suspect this is a simplified range query. This should be labelled as "Simplified Range", and should be treated like any other prediction, not like a range query, because this way this would always end up being ranked too highly.

**Comment by grtlr** [comment]
I just reproduced this. This looks like a bug in the intersection/union logic. This causes our system to find a decision tree with depth = 1. Because we cannot simplify this further, no simplified range is proposed. I'll investigate.

**Comment by grtlr** [comment]
By the way, this is how a simplified range query looks in the prediction list, together with its learned decision rule:

<img width="2115" alt="image" src="https://user-images.githubusercontent.com/3404250/70230606-fbf63900-1758-11ea-8c28-8f2e360cdcca.png">
