### ISSUE TITLE
Add spacing between rows of items

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#250]
This needs a pixel or two between the rows: 

![image](https://user-images.githubusercontent.com/2039375/76240844-8b4c3600-61f9-11ea-8dfe-d80be4aed526.png)

**Comment by kirangadhave** [comment]
![Screen Shot 2020-03-09 at 2 13 32 PM](https://user-images.githubusercontent.com/14944083/76253355-2bad5500-6210-11ea-83ef-1afcf6422348.png)

This okay?

**Comment by alexsb** [comment]
Yes! Looks good.
