### ISSUE TITLE
Design for free-form brush

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#251]
* let's try a gray outline (no fill)
 * provide feedback for clicking, for example by changing color of the outline to the selection color.

**Comment by kirangadhave** [comment]
Yes sorry, the fill was for debugging mouse events. I will fix this

**Comment by kirangadhave** [comment]
![FreeFormbrush](https://user-images.githubusercontent.com/14944083/76257265-ffe19d80-6216-11ea-8c37-7ef0b4b5c40b.gif)

**Comment by alexsb** [comment]
I meant the brush circle, not the rect around the chart. Sorry.

**Comment by kirangadhave** [comment]
Oops

**Comment by kirangadhave** [comment]
![freeformbrush2](https://user-images.githubusercontent.com/14944083/76258627-91eaa580-6219-11ea-8dd8-8499c8d90787.gif)

**Comment by kirangadhave** [comment]
![freeformbrush2](https://user-images.githubusercontent.com/14944083/76258689-b3e42800-6219-11ea-9c29-02ed89dae6f1.gif)

**Comment by alexsb** [comment]
Yes!
