### ISSUE TITLE
Add discrete brush size instead of slider

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#252]
I'd suggest that the largest brush is at 50, the smallest at 20, and one in the middle.

**Comment by kirangadhave** [comment]
![Screen Shot 2020-03-09 at 2 47 11 PM](https://user-images.githubusercontent.com/14944083/76256030-dde71b80-6214-11ea-8dcf-15d1bbdf25e3.png)

**Comment by alexsb** [comment]
See my comment on #253. Also, why is this green?

**Comment by kirangadhave** [comment]
Yeah that is the default colored. changed it to match the rest of the theme.
