### ISSUE TITLE
Make brushing menu a global menu

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#253]
![image](https://user-images.githubusercontent.com/2039375/76241227-4248b180-61fa-11ea-9610-a5ca5911c9ec.png)

This shouldn't be view specific, but should be buttons in the regular tool bar. 

You can simplify this to "Rect." and the three brush sizes I described in #252

**Comment by kirangadhave** [comment]
![Screen Shot 2020-03-09 at 2 47 43 PM](https://user-images.githubusercontent.com/14944083/76256076-f0f9eb80-6214-11ea-8f3c-58b86767116c.png)

**Comment by alexsb** [comment]
Can you do circles of different sizes instead? The numbers don't make sense.

**Comment by kirangadhave** [comment]
![Screen Shot 2020-03-10 at 3 16 20 PM](https://user-images.githubusercontent.com/14944083/76360169-1a347d80-62e2-11ea-9e52-a16e0b1865c4.png)

This okay?
