### ISSUE TITLE
Training workflow

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#263]
First: Task instruction, and user tries to solve problem. Hits submit. 

If more than 60% correct (and we'll figure out that number), say "Well done, you correctly selected 58/95 points. The points you missed are shown in green", Highlight the points, and proceed to next task. 

If less than 60% correct, say "You wrongly selected or missed a lot of points. Please refine your selection and try again."

**Comment by kirangadhave** [comment]
I am implementing this right now with 60%

**Comment by kirangadhave** [comment]
What do we do for excess points? If they select 100 points and reference only includes 30?

**Comment by alexsb** [comment]
jaccard index of > 6  :)
