### ISSUE TITLE
Prediction including old selections

### ISSUE THREAD

**Issue by ZachCutler04** [visdesignlab/intent-system#270]
It seems like prediction selection does not properly “clear” selections, so if I make a selection, clear it, and make another selection, the prediction uses the old selection as well as the new one to make its prediction.

**Comment by kirangadhave** [comment]
Figured this out. Working on the fix now. We were handling it from frontend and i introduced a bug while reworking things.

**Comment by kirangadhave** [comment]
Fixed this issue. Please test and comment if this occurs again.
