### ISSUE TITLE
Can't initiate a rectangle brush from outside the exact area of the scatterplot

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#279]
This is a bit irritating because if you select something at the top, the border isn't even visible. 

Tow solutions: 

1. Make brush work outside of drawing canvas (preferred) 
2. Show gray background only for exact drawing canvas.

**Comment by kirangadhave** [comment]
Sorry moving it to Done was unintended

**Comment by kirangadhave** [comment]
![Rect brush](https://user-images.githubusercontent.com/14944083/77575965-eb013d00-6e99-11ea-8976-dd58ebbbd3d5.gif)
Is this behaviour okay?
