### ISSUE TITLE
Add "escape" mode in training

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#284]
Currently, it's quite hard to get through the training because of the high Jaccard Threshold. 

But even if this is corrected, we need a "way out". I'd suggest, that on the third submit we show the right solution and move on.

People may continue to the main study if they fail fewer than N times, where N is 2?

**Comment by kirangadhave** [comment]
We discussed yesterday that on failing twice we show a hint button that temporarily highlights the solution. Do we do this? or just show them the solution and advance the task?

**Comment by alexsb** [comment]
I like that idea. Let's do that, unless it's extra work. We still need a way to disqualify a participant though?

**Comment by kirangadhave** [comment]
This is not technically difficult. One way to disqualify would be using `N` from above and instead of 2 set it to 4 or 5. If they need hints N times or more. they can't proceed with the main study

**Comment by alexsb** [comment]
OK. We should add: 

Button: "Get a Hint"

"Note that you can use a "Hint" at most three times to qualify for the study".
