### ISSUE TITLE
Move Show Hint button to below the message, Make Click instead of hover

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#285]
![image](https://user-images.githubusercontent.com/2039375/77947502-3e500280-7281-11ea-8718-0cf7c8792735.png)

The Show Hint button should be below the message because it's super easy to hover over it right now, and "strike out". 

Also, make this a click instead of a hover, to avoid involuntary selection.

**Comment by kirangadhave** [comment]
So we click once to show hints, and click again to hide hints? Or just show as long as mouse is clicked?

**Comment by alexsb** [comment]
Maybe as long as mouse is over the button after click?

**Comment by kirangadhave** [comment]
I will add this and push to AWS for testing

**Comment by kirangadhave** [comment]
![Hint](https://user-images.githubusercontent.com/14944083/77951428-490d9600-7287-11ea-8a70-157ae7bee9d6.gif)

Also pushing this to AWS
