### ISSUE TITLE
Make history view left-aligned

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#299]
![image](https://user-images.githubusercontent.com/2039375/80141282-8c95b000-8566-11ea-9fad-01a5ff265bbe.png)

This space is "saved" for branches, but it looks akward. We should move it over to the right only if branches are necessary. It would be acceptable to have horizontal scrolling if branches exist.

**Comment by ZachCutler04** [comment]
View is left aligned and shifts over optimally for the first 3 nodes, allowing the rest to fall off screen
