### ISSUE TITLE
Show full annotation text on tooltip in history view

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#302]
The full text of the event and the full annotation should be shown in a tool tip.

**Comment by ZachCutler04** [comment]
I was under the impression this was already happening? Though I just realized it doesn't work for the Load Dataset, but should work for every other node. Is that the issue?

**Comment by ZachCutler04** [comment]
@alexsb sorry should've tagged you!

**Comment by alexsb** [comment]
It doesn't on my browser/in the live version?

**Comment by ZachCutler04** [comment]
@alexsb This should be fixed now. Once Kiran commits to the live server, let me know if it isn't

**Comment by kirangadhave** [comment]
This is live and i tested it works.
