### ISSUE TITLE
Pick good default configuration for the UI

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#303]
I'd suggest the gapminder dataset, like this: 

![image](https://user-images.githubusercontent.com/2039375/80294330-a6c9bc80-8725-11ea-857c-ba0f0a478ca2.png)

categories on, no selections

**Comment by kirangadhave** [comment]
With two plots ?

**Comment by alexsb** [comment]
Yes, wouldn't you think that's a good combo?

**Comment by kirangadhave** [comment]
This looks like a good combination. Right now i have deployed a version with slightly different plots. I am using those for testing. i will change it back
