### ISSUE TITLE
Align plots to top

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#304]
This looks slightly weird. Should we just align plots to the top instead of center?

![image](https://user-images.githubusercontent.com/2039375/80294354-c4972180-8725-11ea-8e35-b6068bf47eb7.png)

**Comment by kirangadhave** [comment]
![Screen Shot 2020-04-25 at 6 59 44 PM](https://user-images.githubusercontent.com/14944083/80294530-f0ff6d80-8726-11ea-8198-d5f3bbe6bd87.png)

Like this?
