### ISSUE TITLE
Save last selected prediction as intent. 

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#308]
Here, I've locked in a skyline selection. 

![image](https://user-images.githubusercontent.com/2039375/80318663-e0073880-87c8-11ea-80aa-8b7c1864f96b.png)

Right afterwards the "save insight" button shows cluster, because it's the top-ranked prediction. Is that the right thing to do? [It's not]. Probably, we want to preserve the selection of the pattern. 

However, this might actually be a bug: why is skyline not the top predicted pattern in this case?

**Comment by alexsb** [comment]
I think this is due to predictions only being calculated on A/B, not on B/C here.

**Comment by kirangadhave** [comment]
This was a bug!
