### ISSUE TITLE
Find a way to rank range queries

### ISSUE THREAD

**Issue by grtlr** [visdesignlab/intent-system#52]
Right now the rank for range queries is set to constant `0.3`.

**Comment by alexsb** [comment]
Decided on a function of query complexity. If query can be expressed with a single rule, give probability of 1.  Divide 1 by number of rules for other cases. E.g., if you need 4 rules, probability would be 0.25.

**Comment by grtlr** [comment]
In PR #189 I have implemented something similar: the ranking is now computed by `1 / (tree_depth)^2`. I played around with it for a little bit and think the ranking fits in nicely with the scales of the other intents (at least for Jaccard). I will go ahead and close this for now. @alexsb, feel free to reopen it, if you think this needs further improvements.
